### ISSUE TITLE
Add Malaysia prayer time provided by Jakim

### ISSUE THREAD

**Issue by tajjacob** [iamriajul/adhan-flutter#2]
Salam brother,

Can you Add Malaysia prayer time provided by Jakim?

**Comment by iamriajul** [comment]
Waalaikumussalam.
@tajjacob brother please refer to this for details: https://github.com/batoulapps/Adhan/issues/78
In short, you can use SINGAPORE method with little adjustment.

**Comment by iamriajul** [comment]
@tajjacob brother I have recently published a new package which is more flexible, check out adhan for dart: https://pub.dev/packages/adhan
