### ISSUE TITLE
Add the Turkish calculation method (diyanat)

### ISSUE THREAD

**Issue by its-ghaith** [iamriajul/adhan-flutter#3]
I want to program the application of prayer times according to the Turkish method (diyanat). This method is available in the following library in Javascript:
https://github.com/batoulapps/adhan-js/blob/master/src/CalculationMethod.js

And the results of the method should agree with the official website of this method
https://namazvakitleri.diyanet.gov.tr/en-US/

**Comment by iamriajul** [comment]
@ma7amad4088 please use adhan-dart: https://pub.dev/packages/adhan
https://github.com/iamriajul/adhan-dart
In Sha Allah, I'll add Turkey Method to adhan-dart.

**Comment by its-ghaith** [comment]
@iamriajul Thanks for the answer. Please notify me in this issue, when you add the Turkish method to adhan-dart.

**Comment by iamriajul** [comment]
@ma7amad4088 Assalamualaikum brother, I have just released adhan-dart 1.1.13 with added Turkey Method (with Tests coverage!).
