### ISSUE TITLE
How to convert String to Time?

### ISSUE THREAD

**Issue by kusman28** [iamriajul/adhan-flutter#4]
Assalamu alaykum brother,
I'm trying to integrate local notification together with your package.
My problem is to convert it to **Time** since **flutterLocalNotificationsPlugin.showDailyAtTime** only accepts **Time**
and **DateFormat.jm().format(prayerTimes.asr)** is String.

![image](https://user-images.githubusercontent.com/40085614/115952799-b50a0e80-a51a-11eb-96b9-8b3676142b9c.png)

**Comment by iamriajul** [comment]
Waalaikumussalam,
You can convert a DateTime object to Time like this: 
`Time(prayerTimes.fajr.hour, prayerTimes.fajr.minute, prayerTimes.fajr.second)`

Thanks.

**Comment by iamriajul** [comment]
And also consider using this library for prayer times: https://github.com/iamriajul/adhan-dart

**Comment by kusman28** [comment]
I'm always getting this error.
![image](https://user-images.githubusercontent.com/40085614/116259496-6ec9df00-a7a8-11eb-8a8b-f2dc0fe5dac1.png)

**Comment by iamriajul** [comment]
Issue is not here, issue is in the initialization of the PrayerTimes?

**Comment by iamriajul** [comment]
are you using `adhan-dart`?
